import type React from "react"
import type { Metadata } from "next"
import "./globals.css"
import Navbar from "@/components/Navbar"
import WeFooter from "@/components/WeFooter"

export const metadata: Metadata = {
  title: "Celestius",
  description: "Generated by create next app",
  generator: "v0.app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="icon" href="/icon.jpg" type="image/jpeg" />
      </head>
      <body
        className="antialiased pt-[4.5rem] bg-black"
        style={{ fontFamily: "'MyFont', sans-serif" }}
      >
        <Navbar />
        {children}
        <WeFooter />
      </body>
    </html>
  )
}
